version: '3.8'
services:
  dbt_demo:
    build:
      context: .      
    image: etl
    container_name: etl_project
    volumes:
      - ./etl_project:/etl_project
    command: tail -f /dev/null
    ports:
      - "8080:8080"